"""AdminRepository — browse and edit public database tables."""

from __future__ import annotations

import json
import re
from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

import asyncpg

from app.db.connection import close_pool, get_pool


async def _with_fresh_pool_retry(operation):
    """Retry once after closing the pool when a migration invalidated cached plans."""
    try:
        return await operation()
    except asyncpg.exceptions.InvalidCachedStatementError:
        await close_pool()
        return await operation()

_IDENT_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
_AUTO_DEFAULT_MARKERS = (
    "nextval(",
    "now(",
    "current_timestamp",
    "current_date",
    "current_time",
    "clock_timestamp(",
    "transaction_timestamp(",
    "statement_timestamp(",
    "uuid_generate_",
    "gen_random_uuid(",
)


def _is_autogenerated_column(
    *,
    identity: str | None,
    generated: str | None,
    column_default: str | None,
) -> bool:
    if identity in ("a", "d"):
        return True
    if generated == "s":
        return True
    default = (column_default or "").lower()
    if not default:
        return False
    return any(marker in default for marker in _AUTO_DEFAULT_MARKERS)


def _serialize_value(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (dict, list)):
        return value
    if isinstance(value, (bytes, bytearray, memoryview)):
        return value.hex()
    return value


def _serialize_row(row) -> dict[str, Any]:
    return {key: _serialize_value(value) for key, value in dict(row).items()}


def _sql_string_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


_CHECK_IN_RE = re.compile(
    r"\b([A-Za-z_][A-Za-z0-9_]*)\b\s+IN\s*\(([^)]*)\)",
    re.IGNORECASE,
)
_CHECK_ANY_RE = re.compile(
    r"\b([A-Za-z_][A-Za-z0-9_]*)\b\s*=\s*ANY\s*\(\s*ARRAY\[(.*?)\]",
    re.IGNORECASE | re.DOTALL,
)
_SQL_STRING_RE = re.compile(r"'((?:''|[^'])*)'")


def _parse_check_enum_options(definition: str) -> dict[str, list[str]]:
    """Extract column -> allowed string values from a CHECK constraint definition."""
    found: dict[str, list[str]] = {}

    def add(column: str, values: list[str]) -> None:
        if not values:
            return
        # Keep first unique set if multiple clauses mention the same column.
        found.setdefault(column, values)

    for match in _CHECK_IN_RE.finditer(definition):
        column = match.group(1)
        values = [
            item.replace("''", "'") for item in _SQL_STRING_RE.findall(match.group(2))
        ]
        add(column, values)

    for match in _CHECK_ANY_RE.finditer(definition):
        column = match.group(1)
        values = [
            item.replace("''", "'") for item in _SQL_STRING_RE.findall(match.group(2))
        ]
        add(column, values)

    return found


def _coerce_value(value: Any, data_type: str, udt_name: str) -> Any:
    if value is None:
        return None
    if isinstance(value, str) and value.strip() == "":
        return None

    if data_type == "boolean":
        if isinstance(value, bool):
            return value
        text = str(value).strip().lower()
        if text in ("true", "t", "1", "yes"):
            return True
        if text in ("false", "f", "0", "no"):
            return False
        raise ValueError(f"Invalid boolean value: {value!r}")

    if data_type in ("integer", "bigint", "smallint"):
        return int(value)

    if data_type in ("numeric", "double precision", "real", "decimal"):
        return float(value)

    if data_type in ("json", "jsonb") or udt_name in ("json", "jsonb"):
        if isinstance(value, (dict, list)):
            return value
        if isinstance(value, str):
            return json.loads(value)
        raise ValueError(f"Invalid JSON value: {value!r}")

    if data_type == "ARRAY" or udt_name.startswith("_"):
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            return json.loads(value)
        raise ValueError(f"Invalid array value: {value!r}")

    return value


class AdminRepository:
    async def list_tables(self) -> list[str]:
        pool = await get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
        return [row["table_name"] for row in rows]

    def _validate_ident(self, name: str, kind: str) -> None:
        if not _IDENT_PATTERN.match(name):
            raise ValueError(f"Invalid {kind}: {name}")

    async def _table_exists(self, conn, table_name: str) -> bool:
        return bool(
            await conn.fetchval(
                """
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                  AND table_name = $1
                """,
                table_name,
            )
        )

    async def _primary_key_columns(self, conn, table_name: str) -> list[str]:
        rows = await conn.fetch(
            """
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = 'public'
              AND tc.table_name = $1
              AND tc.constraint_type = 'PRIMARY KEY'
            ORDER BY kcu.ordinal_position
            """,
            table_name,
        )
        return [row["column_name"] for row in rows]

    async def _column_meta(
        self, conn, table_name: str, column_name: str
    ) -> dict[str, Any] | None:
        row = await conn.fetchrow(
            """
            SELECT
                column_name,
                data_type,
                udt_name,
                column_default,
                is_nullable,
                is_identity,
                is_generated
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = $1
              AND column_name = $2
            """,
            table_name,
            column_name,
        )
        if row is None:
            return None
        return dict(row)

    async def _all_columns_meta(self, conn, table_name: str) -> list[dict[str, Any]]:
        rows = await conn.fetch(
            """
            SELECT
                column_name,
                data_type,
                udt_name,
                column_default,
                is_nullable,
                is_identity,
                is_generated
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = $1
            ORDER BY ordinal_position
            """,
            table_name,
        )
        return [dict(row) for row in rows]

    async def _foreign_keys(self, conn, table_name: str) -> dict[str, dict[str, str]]:
        rows = await conn.fetch(
            """
            SELECT
                att.attname AS column_name,
                ref_table.relname AS foreign_table,
                ref_att.attname AS foreign_column
            FROM pg_catalog.pg_constraint con
            JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid
            JOIN pg_catalog.pg_namespace nsp ON nsp.oid = rel.relnamespace
            JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS cols(attnum, ord)
              ON TRUE
            JOIN pg_catalog.pg_attribute att
              ON att.attrelid = con.conrelid
             AND att.attnum = cols.attnum
            JOIN pg_catalog.pg_class ref_table ON ref_table.oid = con.confrelid
            JOIN LATERAL unnest(con.confkey) WITH ORDINALITY AS ref_cols(attnum, ord)
              ON ref_cols.ord = cols.ord
            JOIN pg_catalog.pg_attribute ref_att
              ON ref_att.attrelid = con.confrelid
             AND ref_att.attnum = ref_cols.attnum
            WHERE con.contype = 'f'
              AND nsp.nspname = 'public'
              AND rel.relname = $1
            ORDER BY cols.ord
            """,
            table_name,
        )
        foreign_keys: dict[str, dict[str, str]] = {}
        for row in rows:
            column = row["column_name"]
            if column in foreign_keys:
                continue
            foreign_keys[column] = {
                "table": row["foreign_table"],
                "column": row["foreign_column"],
            }
        return foreign_keys

    async def _check_constraint_options(
        self,
        conn,
        table_name: str,
    ) -> dict[str, list[dict[str, Any]]]:
        rows = await conn.fetch(
            """
            SELECT pg_get_constraintdef(c.oid) AS definition
            FROM pg_catalog.pg_constraint c
            JOIN pg_catalog.pg_class rel ON rel.oid = c.conrelid
            JOIN pg_catalog.pg_namespace nsp ON nsp.oid = rel.relnamespace
            WHERE c.contype = 'c'
              AND nsp.nspname = 'public'
              AND rel.relname = $1
            """,
            table_name,
        )
        options: dict[str, list[dict[str, Any]]] = {}
        for row in rows:
            parsed = _parse_check_enum_options(row["definition"] or "")
            for column, values in parsed.items():
                if column in options:
                    continue
                options[column] = [
                    {"value": value, "label": value} for value in values
                ]
        return options

    async def _label_column(
        self, conn, table_name: str, value_column: str
    ) -> str | None:
        columns = [
            row["column_name"]
            for row in await conn.fetch(
                """
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = $1
                ORDER BY ordinal_position
                """,
                table_name,
            )
        ]
        for candidate in (
            "slug",
            "name_en",
            "name",
            "code",
            "title",
            "label",
            "keyword",
        ):
            if candidate in columns and candidate != value_column:
                return candidate
        return None

    async def _foreign_key_options(
        self,
        conn,
        *,
        foreign_table: str,
        foreign_column: str,
        limit: int = 500,
    ) -> list[dict[str, Any]]:
        self._validate_ident(foreign_table, "table name")
        self._validate_ident(foreign_column, "column name")

        label_column = await self._label_column(conn, foreign_table, foreign_column)
        if label_column:
            self._validate_ident(label_column, "column name")
            rows = await conn.fetch(
                f'SELECT "{foreign_column}" AS value, '
                f'"{label_column}" AS label '
                f'FROM "{foreign_table}" '
                f'ORDER BY "{label_column}", "{foreign_column}" '
                f"LIMIT $1",
                limit,
            )
            options = []
            for row in rows:
                value = _serialize_value(row["value"])
                label = row["label"]
                label_text = (
                    f"{value} — {label}"
                    if label is not None and str(label) != str(value)
                    else str(value)
                )
                options.append({"value": value, "label": label_text})
            return options

        rows = await conn.fetch(
            f'SELECT "{foreign_column}" AS value '
            f'FROM "{foreign_table}" '
            f'ORDER BY "{foreign_column}" '
            f"LIMIT $1",
            limit,
        )
        return [
            {
                "value": _serialize_value(row["value"]),
                "label": str(_serialize_value(row["value"])),
            }
            for row in rows
        ]

    async def fetch_table(
        self,
        table_name: str,
        *,
        limit: int = 100,
        offset: int = 0,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        return await _with_fresh_pool_retry(
            lambda: self._fetch_table_once(
                table_name, limit=limit, offset=offset
            )
        )

    async def _fetch_table_once(
        self,
        table_name: str,
        *,
        limit: int,
        offset: int,
    ) -> dict[str, Any]:
        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            total = await conn.fetchval(f'SELECT COUNT(*) FROM "{table_name}"')
            rows = await conn.fetch(
                f'SELECT * FROM "{table_name}" LIMIT $1 OFFSET $2',
                limit,
                offset,
            )
            column_rows = await conn.fetch(
                """
                SELECT
                    a.attname AS column_name,
                    format_type(a.atttypid, a.atttypmod) AS data_type,
                    col_description(a.attrelid, a.attnum) AS comment,
                    pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
                    a.attidentity AS identity,
                    a.attgenerated AS generated,
                    a.attnotnull AS not_null
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_catalog.pg_attrdef ad
                  ON ad.adrelid = a.attrelid
                 AND ad.adnum = a.attnum
                WHERE n.nspname = 'public'
                  AND c.relname = $1
                  AND c.relkind = 'r'
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                table_name,
            )
            primary_key = await self._primary_key_columns(conn, table_name)
            foreign_keys = await self._foreign_keys(conn, table_name)
            column_options: dict[str, list[dict[str, Any]]] = {}
            for column, reference in foreign_keys.items():
                column_options[column] = await self._foreign_key_options(
                    conn,
                    foreign_table=reference["table"],
                    foreign_column=reference["column"],
                )
            for column, options in (
                await self._check_constraint_options(conn, table_name)
            ).items():
                column_options.setdefault(column, options)

        serialized_rows = [_serialize_row(row) for row in rows]
        columns = [row["column_name"] for row in column_rows]
        column_comments = {
            row["column_name"]: row["comment"] for row in column_rows
        }
        column_types = {
            row["column_name"]: row["data_type"] for row in column_rows
        }
        required_columns = [
            row["column_name"]
            for row in column_rows
            if row["not_null"]
            and not _is_autogenerated_column(
                identity=row["identity"],
                generated=row["generated"],
                column_default=row["column_default"],
            )
        ]
        auto_columns = [
            row["column_name"]
            for row in column_rows
            if _is_autogenerated_column(
                identity=row["identity"],
                generated=row["generated"],
                column_default=row["column_default"],
            )
        ]

        return {
            "table": table_name,
            "columns": columns,
            "column_comments": column_comments,
            "column_types": column_types,
            "required_columns": required_columns,
            "auto_columns": auto_columns,
            "foreign_keys": foreign_keys,
            "column_options": column_options,
            "primary_key": primary_key,
            "rows": serialized_rows,
            "total": total,
            "limit": limit,
            "offset": offset,
        }

    async def update_column_comment(
        self,
        table_name: str,
        column: str,
        *,
        comment: str | None,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        self._validate_ident(column, "column name")

        normalized = comment.strip() if isinstance(comment, str) else comment
        if normalized == "":
            normalized = None
        if normalized is not None and len(normalized) > 4000:
            raise ValueError("Comment must be at most 4000 characters.")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            meta = await self._column_meta(conn, table_name, column)
            if meta is None:
                raise ValueError(f"Column '{column}' was not found.")

            await conn.execute(
                f'COMMENT ON COLUMN "{table_name}"."{column}" '
                f"IS {_sql_string_literal(normalized)}"
            )

        return {
            "table": table_name,
            "column": column,
            "comment": normalized,
        }

    async def insert_row(
        self,
        table_name: str,
        *,
        values: dict[str, Any],
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        return await _with_fresh_pool_retry(
            lambda: self._insert_row_once(table_name, values=values)
        )

    async def _insert_row_once(
        self,
        table_name: str,
        *,
        values: dict[str, Any],
    ) -> dict[str, Any]:
        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            metas = await self._all_columns_meta(conn, table_name)
            if not metas:
                raise ValueError(f"Table '{table_name}' has no columns.")

            meta_by_name = {meta["column_name"]: meta for meta in metas}
            for column in values:
                self._validate_ident(column, "column name")
                if column not in meta_by_name:
                    raise ValueError(f"Column '{column}' was not found.")

            insert_columns: list[str] = []
            params: list[Any] = []
            for meta in metas:
                column = meta["column_name"]
                if meta["is_generated"] == "ALWAYS":
                    continue

                raw = values.get(column)
                is_empty = raw is None or (isinstance(raw, str) and raw.strip() == "")
                if is_empty:
                    if meta["is_identity"] == "YES" or meta["column_default"] is not None:
                        continue
                    insert_columns.append(column)
                    params.append(None)
                    continue

                try:
                    coerced = _coerce_value(raw, meta["data_type"], meta["udt_name"])
                except (TypeError, ValueError, json.JSONDecodeError) as exc:
                    raise ValueError(
                        f"Invalid value for column '{column}': {exc}"
                    ) from exc

                insert_columns.append(column)
                params.append(coerced)

            if not insert_columns:
                row = await conn.fetchrow(
                    f'INSERT INTO "{table_name}" DEFAULT VALUES RETURNING *'
                )
            else:
                columns_sql = ", ".join(f'"{column}"' for column in insert_columns)
                placeholders = ", ".join(
                    f"${index}" for index in range(1, len(params) + 1)
                )
                row = await conn.fetchrow(
                    f'INSERT INTO "{table_name}" ({columns_sql}) '
                    f"VALUES ({placeholders}) RETURNING *",
                    *params,
                )

        return {
            "table": table_name,
            "row": _serialize_row(row),
        }

    async def update_cell(
        self,
        table_name: str,
        *,
        primary_key: dict[str, Any],
        column: str,
        value: Any,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        self._validate_ident(column, "column name")
        return await _with_fresh_pool_retry(
            lambda: self._update_cell_once(
                table_name,
                primary_key=primary_key,
                column=column,
                value=value,
            )
        )

    async def _update_cell_once(
        self,
        table_name: str,
        *,
        primary_key: dict[str, Any],
        column: str,
        value: Any,
    ) -> dict[str, Any]:
        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            pk_columns = await self._primary_key_columns(conn, table_name)
            if not pk_columns:
                raise ValueError(f"Table '{table_name}' has no primary key.")

            if set(primary_key.keys()) != set(pk_columns):
                raise ValueError(
                    f"Primary key must include exactly: {', '.join(pk_columns)}"
                )

            for pk_column in pk_columns:
                self._validate_ident(pk_column, "column name")

            if column in pk_columns:
                raise ValueError("Primary key columns cannot be edited.")

            meta = await self._column_meta(conn, table_name, column)
            if meta is None:
                raise ValueError(f"Column '{column}' was not found.")

            try:
                coerced = _coerce_value(value, meta["data_type"], meta["udt_name"])
            except (TypeError, ValueError, json.JSONDecodeError) as exc:
                raise ValueError(f"Invalid value for column '{column}': {exc}") from exc

            where_parts = []
            params: list[Any] = [coerced]
            for index, pk_column in enumerate(pk_columns, start=2):
                where_parts.append(f'"{pk_column}" = ${index}')
                params.append(primary_key[pk_column])

            row = await conn.fetchrow(
                f'UPDATE "{table_name}" SET "{column}" = $1 '
                f'WHERE {" AND ".join(where_parts)} '
                f"RETURNING *",
                *params,
            )

            if row is None:
                raise LookupError("row")

        return {
            "table": table_name,
            "column": column,
            "value": _serialize_value(row[column]),
            "row": _serialize_row(row),
        }

    async def delete_rows(
        self,
        table_name: str,
        *,
        rows: list[dict[str, Any]],
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        if not rows:
            raise ValueError("At least one row is required.")
        if len(rows) > 100:
            raise ValueError("Cannot delete more than 100 rows at once.")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            pk_columns = await self._primary_key_columns(conn, table_name)
            if not pk_columns:
                raise ValueError(f"Table '{table_name}' has no primary key.")

            for pk_column in pk_columns:
                self._validate_ident(pk_column, "column name")

            deleted = 0
            async with conn.transaction():
                for primary_key in rows:
                    if set(primary_key.keys()) != set(pk_columns):
                        raise ValueError(
                            f"Primary key must include exactly: {', '.join(pk_columns)}"
                        )

                    where_parts = []
                    params: list[Any] = []
                    for index, pk_column in enumerate(pk_columns, start=1):
                        where_parts.append(f'"{pk_column}" = ${index}')
                        params.append(primary_key[pk_column])

                    result = await conn.execute(
                        f'DELETE FROM "{table_name}" '
                        f'WHERE {" AND ".join(where_parts)}',
                        *params,
                    )
                    deleted += int(result.split()[-1])

        return {
            "table": table_name,
            "deleted": deleted,
        }
