"""AdminRepository — browse and edit public database tables."""

from __future__ import annotations

import json
import re
from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID

from app.db.connection import get_pool

_IDENT_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
_AUTO_DEFAULT_MARKERS = (
    "nextval(",
    "now(",
    "current_timestamp",
    "current_date",
    "current_time",
    "clock_timestamp(",
    "transaction_timestamp(",
    "statement_timestamp(",
    "uuid_generate_",
    "gen_random_uuid(",
)


def _is_autogenerated_column(
    *,
    identity: str | None,
    generated: str | None,
    column_default: str | None,
) -> bool:
    if identity in ("a", "d"):
        return True
    if generated == "s":
        return True
    default = (column_default or "").lower()
    if not default:
        return False
    return any(marker in default for marker in _AUTO_DEFAULT_MARKERS)


def _serialize_value(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, UUID):
        return str(value)
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (dict, list)):
        return value
    if isinstance(value, (bytes, bytearray, memoryview)):
        return value.hex()
    return value


def _serialize_row(row) -> dict[str, Any]:
    return {key: _serialize_value(value) for key, value in dict(row).items()}


def _sql_string_literal(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def _coerce_value(value: Any, data_type: str, udt_name: str) -> Any:
    if value is None:
        return None
    if isinstance(value, str) and value.strip() == "":
        return None

    if data_type == "boolean":
        if isinstance(value, bool):
            return value
        text = str(value).strip().lower()
        if text in ("true", "t", "1", "yes"):
            return True
        if text in ("false", "f", "0", "no"):
            return False
        raise ValueError(f"Invalid boolean value: {value!r}")

    if data_type in ("integer", "bigint", "smallint"):
        return int(value)

    if data_type in ("numeric", "double precision", "real", "decimal"):
        return float(value)

    if data_type in ("json", "jsonb") or udt_name in ("json", "jsonb"):
        if isinstance(value, (dict, list)):
            return value
        if isinstance(value, str):
            return json.loads(value)
        raise ValueError(f"Invalid JSON value: {value!r}")

    if data_type == "ARRAY" or udt_name.startswith("_"):
        if isinstance(value, list):
            return value
        if isinstance(value, str):
            return json.loads(value)
        raise ValueError(f"Invalid array value: {value!r}")

    return value


class AdminRepository:
    async def list_tables(self) -> list[str]:
        pool = await get_pool()
        async with pool.acquire() as conn:
            rows = await conn.fetch(
                """
                SELECT table_name
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                ORDER BY table_name
                """
            )
        return [row["table_name"] for row in rows]

    def _validate_ident(self, name: str, kind: str) -> None:
        if not _IDENT_PATTERN.match(name):
            raise ValueError(f"Invalid {kind}: {name}")

    async def _table_exists(self, conn, table_name: str) -> bool:
        return bool(
            await conn.fetchval(
                """
                SELECT 1
                FROM information_schema.tables
                WHERE table_schema = 'public'
                  AND table_type = 'BASE TABLE'
                  AND table_name = $1
                """,
                table_name,
            )
        )

    async def _primary_key_columns(self, conn, table_name: str) -> list[str]:
        rows = await conn.fetch(
            """
            SELECT kcu.column_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON tc.constraint_name = kcu.constraint_name
             AND tc.table_schema = kcu.table_schema
            WHERE tc.table_schema = 'public'
              AND tc.table_name = $1
              AND tc.constraint_type = 'PRIMARY KEY'
            ORDER BY kcu.ordinal_position
            """,
            table_name,
        )
        return [row["column_name"] for row in rows]

    async def _column_meta(
        self, conn, table_name: str, column_name: str
    ) -> dict[str, Any] | None:
        row = await conn.fetchrow(
            """
            SELECT
                column_name,
                data_type,
                udt_name,
                column_default,
                is_nullable,
                is_identity,
                is_generated
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = $1
              AND column_name = $2
            """,
            table_name,
            column_name,
        )
        if row is None:
            return None
        return dict(row)

    async def _all_columns_meta(self, conn, table_name: str) -> list[dict[str, Any]]:
        rows = await conn.fetch(
            """
            SELECT
                column_name,
                data_type,
                udt_name,
                column_default,
                is_nullable,
                is_identity,
                is_generated
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = $1
            ORDER BY ordinal_position
            """,
            table_name,
        )
        return [dict(row) for row in rows]

    async def fetch_table(
        self,
        table_name: str,
        *,
        limit: int = 100,
        offset: int = 0,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            total = await conn.fetchval(f'SELECT COUNT(*) FROM "{table_name}"')
            rows = await conn.fetch(
                f'SELECT * FROM "{table_name}" LIMIT $1 OFFSET $2',
                limit,
                offset,
            )
            column_rows = await conn.fetch(
                """
                SELECT
                    a.attname AS column_name,
                    format_type(a.atttypid, a.atttypmod) AS data_type,
                    col_description(a.attrelid, a.attnum) AS comment,
                    pg_get_expr(ad.adbin, ad.adrelid) AS column_default,
                    a.attidentity AS identity,
                    a.attgenerated AS generated
                FROM pg_catalog.pg_attribute a
                JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
                JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                LEFT JOIN pg_catalog.pg_attrdef ad
                  ON ad.adrelid = a.attrelid
                 AND ad.adnum = a.attnum
                WHERE n.nspname = 'public'
                  AND c.relname = $1
                  AND c.relkind = 'r'
                  AND a.attnum > 0
                  AND NOT a.attisdropped
                ORDER BY a.attnum
                """,
                table_name,
            )
            primary_key = await self._primary_key_columns(conn, table_name)

        serialized_rows = [_serialize_row(row) for row in rows]
        columns = [row["column_name"] for row in column_rows]
        column_comments = {
            row["column_name"]: row["comment"] for row in column_rows
        }
        column_types = {
            row["column_name"]: row["data_type"] for row in column_rows
        }
        auto_columns = [
            row["column_name"]
            for row in column_rows
            if _is_autogenerated_column(
                identity=row["identity"],
                generated=row["generated"],
                column_default=row["column_default"],
            )
        ]

        return {
            "table": table_name,
            "columns": columns,
            "column_comments": column_comments,
            "column_types": column_types,
            "auto_columns": auto_columns,
            "primary_key": primary_key,
            "rows": serialized_rows,
            "total": total,
            "limit": limit,
            "offset": offset,
        }

    async def update_column_comment(
        self,
        table_name: str,
        column: str,
        *,
        comment: str | None,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        self._validate_ident(column, "column name")

        normalized = comment.strip() if isinstance(comment, str) else comment
        if normalized == "":
            normalized = None
        if normalized is not None and len(normalized) > 4000:
            raise ValueError("Comment must be at most 4000 characters.")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            meta = await self._column_meta(conn, table_name, column)
            if meta is None:
                raise ValueError(f"Column '{column}' was not found.")

            await conn.execute(
                f'COMMENT ON COLUMN "{table_name}"."{column}" '
                f"IS {_sql_string_literal(normalized)}"
            )

        return {
            "table": table_name,
            "column": column,
            "comment": normalized,
        }

    async def insert_row(
        self,
        table_name: str,
        *,
        values: dict[str, Any],
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            metas = await self._all_columns_meta(conn, table_name)
            if not metas:
                raise ValueError(f"Table '{table_name}' has no columns.")

            meta_by_name = {meta["column_name"]: meta for meta in metas}
            for column in values:
                self._validate_ident(column, "column name")
                if column not in meta_by_name:
                    raise ValueError(f"Column '{column}' was not found.")

            insert_columns: list[str] = []
            params: list[Any] = []
            for meta in metas:
                column = meta["column_name"]
                if meta["is_generated"] == "ALWAYS":
                    continue

                raw = values.get(column)
                is_empty = raw is None or (isinstance(raw, str) and raw.strip() == "")
                if is_empty:
                    if meta["is_identity"] == "YES" or meta["column_default"] is not None:
                        continue
                    insert_columns.append(column)
                    params.append(None)
                    continue

                try:
                    coerced = _coerce_value(raw, meta["data_type"], meta["udt_name"])
                except (TypeError, ValueError, json.JSONDecodeError) as exc:
                    raise ValueError(
                        f"Invalid value for column '{column}': {exc}"
                    ) from exc

                insert_columns.append(column)
                params.append(coerced)

            if not insert_columns:
                row = await conn.fetchrow(
                    f'INSERT INTO "{table_name}" DEFAULT VALUES RETURNING *'
                )
            else:
                columns_sql = ", ".join(f'"{column}"' for column in insert_columns)
                placeholders = ", ".join(
                    f"${index}" for index in range(1, len(params) + 1)
                )
                row = await conn.fetchrow(
                    f'INSERT INTO "{table_name}" ({columns_sql}) '
                    f"VALUES ({placeholders}) RETURNING *",
                    *params,
                )

        return {
            "table": table_name,
            "row": _serialize_row(row),
        }

    async def update_cell(
        self,
        table_name: str,
        *,
        primary_key: dict[str, Any],
        column: str,
        value: Any,
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        self._validate_ident(column, "column name")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            pk_columns = await self._primary_key_columns(conn, table_name)
            if not pk_columns:
                raise ValueError(f"Table '{table_name}' has no primary key.")

            if set(primary_key.keys()) != set(pk_columns):
                raise ValueError(
                    f"Primary key must include exactly: {', '.join(pk_columns)}"
                )

            for pk_column in pk_columns:
                self._validate_ident(pk_column, "column name")

            if column in pk_columns:
                raise ValueError("Primary key columns cannot be edited.")

            meta = await self._column_meta(conn, table_name, column)
            if meta is None:
                raise ValueError(f"Column '{column}' was not found.")

            try:
                coerced = _coerce_value(value, meta["data_type"], meta["udt_name"])
            except (TypeError, ValueError, json.JSONDecodeError) as exc:
                raise ValueError(f"Invalid value for column '{column}': {exc}") from exc

            where_parts = []
            params: list[Any] = [coerced]
            for index, pk_column in enumerate(pk_columns, start=2):
                where_parts.append(f'"{pk_column}" = ${index}')
                params.append(primary_key[pk_column])

            row = await conn.fetchrow(
                f'UPDATE "{table_name}" SET "{column}" = $1 '
                f'WHERE {" AND ".join(where_parts)} '
                f"RETURNING *",
                *params,
            )

            if row is None:
                raise LookupError("row")

        return {
            "table": table_name,
            "column": column,
            "value": _serialize_value(row[column]),
            "row": _serialize_row(row),
        }

    async def delete_rows(
        self,
        table_name: str,
        *,
        rows: list[dict[str, Any]],
    ) -> dict[str, Any]:
        self._validate_ident(table_name, "table name")
        if not rows:
            raise ValueError("At least one row is required.")
        if len(rows) > 100:
            raise ValueError("Cannot delete more than 100 rows at once.")

        pool = await get_pool()
        async with pool.acquire() as conn:
            if not await self._table_exists(conn, table_name):
                raise LookupError(table_name)

            pk_columns = await self._primary_key_columns(conn, table_name)
            if not pk_columns:
                raise ValueError(f"Table '{table_name}' has no primary key.")

            for pk_column in pk_columns:
                self._validate_ident(pk_column, "column name")

            deleted = 0
            async with conn.transaction():
                for primary_key in rows:
                    if set(primary_key.keys()) != set(pk_columns):
                        raise ValueError(
                            f"Primary key must include exactly: {', '.join(pk_columns)}"
                        )

                    where_parts = []
                    params: list[Any] = []
                    for index, pk_column in enumerate(pk_columns, start=1):
                        where_parts.append(f'"{pk_column}" = ${index}')
                        params.append(primary_key[pk_column])

                    result = await conn.execute(
                        f'DELETE FROM "{table_name}" '
                        f'WHERE {" AND ".join(where_parts)}',
                        *params,
                    )
                    deleted += int(result.split()[-1])

        return {
            "table": table_name,
            "deleted": deleted,
        }
