/**
 * Tailwind v3-style preset (reference / non-v4 consumers).
 * The frontend uses Tailwind v4 — see design/ethos-theme.css instead.
 */
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: {
        background: '#faf9f5',
        surface: '#faf9f5',
        'surface-dim': '#dbdad6',
        'surface-bright': '#faf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f4f0',
        'surface-container': '#efeeea',
        'surface-container-high': '#e9e8e4',
        'surface-container-highest': '#e3e2df',
        'surface-variant': '#e3e2df',
        'on-background': '#1b1c1a',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#494740',
        'text-tertiary': '#A09E96',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1d1b18',
        'on-primary-container': '#86837f',
        secondary: '#605e56',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3dfd4',
        'on-secondary-container': '#65635a',
        outline: '#7a776f',
        'outline-variant': '#cbc6bd',
        'border-subtle': '#E4E2DB',
        'border-emphasis': '#CBC9C1',
        'replacement-bg': '#EAF3DE',
        'replacement-text': '#27500A',
        'replacement-border': '#639922',
        'reduction-bg': '#FAEEDA',
        'reduction-text': '#633806',
        'reduction-border': '#BA7517',
        'refinement-bg': '#E1F5EE',
        'refinement-text': '#085041',
        'refinement-border': '#1D9E75',
        'info-bg': '#E6F1FB',
        'info-text': '#0C447C',
        'info-border': '#378ADD',
        'jurisdiction-intl-only-bg': '#F1EFE8',
        'jurisdiction-intl-only-text': '#5F5E5A',
        'jurisdiction-intl-only-border': '#B4B2A9',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '24px',
        'section-gap': '48px',
        'card-gap': '16px',
        'element-gap': '12px',
        'fine-gap': '8px',
        gutter: '16px',
        'margin-label': '14px',
      },
      fontFamily: {
        'body-base': ['DM Sans', 'system-ui', 'sans-serif'],
        'headline-lg': ['DM Sans', 'system-ui', 'sans-serif'],
        'nav-logo': ['DM Sans', 'system-ui', 'sans-serif'],
        'nav-link': ['DM Sans', 'system-ui', 'sans-serif'],
        'card-title': ['DM Sans', 'system-ui', 'sans-serif'],
        'label-caps': ['DM Sans', 'system-ui', 'sans-serif'],
        metadata: ['DM Sans', 'system-ui', 'sans-serif'],
        'badge-button': ['DM Sans', 'system-ui', 'sans-serif'],
        'small-label': ['DM Sans', 'system-ui', 'sans-serif'],
        'monospace-data': ['DM Mono', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['17px', { lineHeight: '24px', fontWeight: '500' }],
        'body-base': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'nav-logo': ['14px', { letterSpacing: '-0.01em', fontWeight: '500' }],
        'nav-link': ['13px', { lineHeight: 'normal', fontWeight: '400' }],
        'card-title': ['13px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['13px', { letterSpacing: '0.04em', fontWeight: '500' }],
        metadata: ['12px', { lineHeight: 'normal', fontWeight: '400' }],
        'badge-button': ['12px', { lineHeight: 'normal', fontWeight: '500' }],
        'small-label': ['11px', { letterSpacing: '0.06em', fontWeight: '500' }],
        'monospace-data': ['12px', { lineHeight: 'normal', fontWeight: '400' }],
      },
      maxWidth: {
        content: '80rem',
      },
      height: {
        nav: '64px',
      },
      transitionDuration: {
        ethos: '120ms',
      },
    },
  },
};
